#!/usr/bin/env node
// Fetch IBM VGA 8x16 CP437 font, convert to hex-encoded JS module.
// Run once: node tools/fetch-font.mjs
//
// If the primary URL is unreachable, provide your own public-domain
// CP437 4096-byte binary via FONT_PATH env var:
//   FONT_PATH=./my-font.F16 node tools/fetch-font.mjs

import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { request } from 'node:https';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '..', 'plugins', 'claude-garden', 'sidecar', 'font-cp437.mjs');

const PRIMARY_URL = 'https://raw.githubusercontent.com/viler-int10h/vga-text-mode-fonts/master/FONTS/PC-IBM/VGA8.F16';

function fetchHttps(url) {
  return new Promise((resolve, reject) => {
    request(url, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode}`));
        return;
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', reject).end();
  });
}

async function fetchFont() {
  const fontPath = process.env.FONT_PATH;
  if (fontPath) {
    console.log(`Reading font from ${fontPath}`);
    return readFileSync(fontPath);
  }
  console.log(`Fetching font from ${PRIMARY_URL}`);
  return await fetchHttps(PRIMARY_URL);
}

function toHexChunks(buf, perLine = 32) {
  const lines = [];
  for (let i = 0; i < buf.length; i += perLine) {
    lines.push('  "' + buf.slice(i, i + perLine).toString('hex') + '"');
  }
  return lines.join(' +\n');
}

const buf = await fetchFont();
if (buf.length !== 4096) {
  throw new Error(`Expected 4096 bytes, got ${buf.length}`);
}

const out = `// CP437 VGA 8x16 bitmap font (public domain).
// 256 glyphs × 16 bytes each = 4096 bytes.
// Each byte is one row of 8 pixels (MSB = leftmost pixel).
// Generated by tools/fetch-font.mjs — do not edit by hand.

const FONT_HEX =
${toHexChunks(buf)};

export const FONT_CP437 = Uint8Array.from(
  FONT_HEX.match(/.{2}/g).map(h => parseInt(h, 16))
);

export const GLYPH_HEIGHT = 16;
export const GLYPH_WIDTH = 8;

// Get the 16-byte glyph for a CP437 codepoint (0-255).
export function getGlyph(cp) {
  if (cp < 0 || cp > 255) cp = 0x3F; // '?'
  return FONT_CP437.subarray(cp * 16, cp * 16 + 16);
}

// Unicode → CP437 mapping for characters used by the card.
// Characters not in this table fall back to '?' (0x3F).
// CP437 does NOT have heavy box-drawing chars (┏━┓┃...), so they
// map to the nearest light-box or double-box equivalent.
export const UNICODE_TO_CP437 = {
  // ASCII passthrough (0x20-0x7E map to themselves)
  // Double box drawing (Claude Garden card border)
  0x2550: 0xCD, 0x2551: 0xBA, 0x2554: 0xC9, 0x2557: 0xBB,
  0x255A: 0xC8, 0x255D: 0xBC, 0x2560: 0xCC, 0x2563: 0xB9,
  0x2566: 0xCB, 0x2569: 0xCA, 0x256C: 0xCE,
  // Light box drawing
  0x2500: 0xC4, 0x2502: 0xB3, 0x250C: 0xDA, 0x2510: 0xBF,
  0x2514: 0xC0, 0x2518: 0xD9, 0x251C: 0xC3, 0x2524: 0xB4,
  0x252C: 0xC2, 0x2534: 0xC1, 0x253C: 0xC5,
  // Heavy box drawing → map to light box (CP437 has no heavy)
  0x250F: 0xDA, // ┏ → ┌
  0x2501: 0xC4, // ━ → ─
  0x2513: 0xBF, // ┓ → ┐
  0x2503: 0xB3, // ┃ → │
  0x2517: 0xC0, // ┗ → └
  0x251B: 0xD9, // ┛ → ┘
  0x2533: 0xC2, // ┳ → ┬
  0x253B: 0xC1, // ┻ → ┴
  0x252B: 0xB4, // ┫ → ┤
  0x2523: 0xC3, // ┣ → ├
  // Block elements used in sprites
  0x2580: 0xDF, // ▀ upper half
  0x2584: 0xDC, // ▄ lower half
  0x2588: 0xDB, // █ full block
  0x2591: 0xB0, // ░ light shade
  0x2592: 0xB1, // ▒ medium shade
  0x2593: 0xB2, // ▓ dark shade
  // Quadrant/partial blocks — map to nearest full/half block
  0x2581: 0xDC, // ▁ → ▄ (lower half)
  0x2582: 0xDC,
  0x2583: 0xDC,
  0x2585: 0xDB,
  0x2586: 0xDB,
  0x2587: 0xDB,
  0x2596: 0xDC, // ▖ lower-left quadrant → ▄
  0x2597: 0xDC, // ▗ lower-right quadrant → ▄
  0x2598: 0xDF, // ▘ upper-left quadrant → ▀
  0x2599: 0xDB, // ▙ → █
  0x259B: 0xDB, // ▛ → █
  0x259C: 0xDB, // ▜ → █
  0x259D: 0xDF, // ▝ upper-right quadrant → ▀
  0x259F: 0xDB, // ▟ → █
  0x258C: 0xDD, // ▌ left half
  0x2590: 0xDE, // ▐ right half
  // Common symbols
  0x2605: 0x2A, // ★ → *
  0x2661: 0x03, // ♡ → CP437 heart (♥)
};

export function unicodeToCp437(ch) {
  const cp = ch.codePointAt(0);
  if (cp === undefined) return 0x20;
  if (cp >= 0x20 && cp <= 0x7E) return cp; // ASCII
  return UNICODE_TO_CP437[cp] ?? 0x3F; // '?'
}
`;

writeFileSync(OUT_PATH, out);
console.log(`Wrote ${OUT_PATH} (${out.length} bytes)`);
